// Shared British to American spelling table.
// Used by tools/fix-blog-prose.mjs to rewrite the posts and by
// tools/verify/blog-parity.mjs to normalise both sides of the comparison,
// so the two can never drift apart.
export const SPELLING = {
  optimisation: 'optimization', optimisations: 'optimizations',
  optimise: 'optimize', optimises: 'optimizes', optimised: 'optimized',
  optimising: 'optimizing', unoptimised: 'unoptimized',
  underoptimised: 'underoptimized',
  prioritise: 'prioritize', prioritises: 'prioritizes', prioritised: 'prioritized',
  prioritising: 'prioritizing', prioritisation: 'prioritization',
  deprioritise: 'deprioritize', deprioritised: 'deprioritized',
  personalisation: 'personalization', personalise: 'personalize',
  personalised: 'personalized',
  organisation: 'organization', organisations: 'organizations',
  organise: 'organize', organises: 'organizes', organised: 'organized',
  organising: 'organizing', reorganised: 'reorganized',
  reorganisations: 'reorganizations',
  recognise: 'recognize', recognises: 'recognizes', recognised: 'recognized',
  recognising: 'recognizing',
  minimise: 'minimize', minimised: 'minimized', minimising: 'minimizing',
  maximise: 'maximize', maximises: 'maximizes', maximising: 'maximizing',
  synthesise: 'synthesize', synthesises: 'synthesizes', synthesised: 'synthesized',
  synthesising: 'synthesizing',
  utilise: 'utilize', underutilise: 'underutilize', underutilised: 'underutilized',
  underutilising: 'underutilizing',
  categorise: 'categorize', categorises: 'categorizes', categorised: 'categorized',
  categorising: 'categorizing', categorisation: 'categorization',
  emphasise: 'emphasize', emphasises: 'emphasizes', emphasised: 'emphasized',
  emphasising: 'emphasizing',
  realise: 'realize', realises: 'realizes', realised: 'realized',
  realising: 'realizing', realisation: 'realization',
  standardise: 'standardize', standardised: 'standardized',
  standardising: 'standardizing', standardisation: 'standardization',
  summarise: 'summarize', summarises: 'summarizes', summarised: 'summarized',
  summarising: 'summarizing', summarisation: 'summarization',
  penalise: 'penalize', penalises: 'penalizes', penalised: 'penalized',
  penalising: 'penalizing',
  incentivise: 'incentivize', specialise: 'specialize', specialised: 'specialized',
  specialisation: 'specialization',
  materialise: 'materialize', materialised: 'materialized',
  customise: 'customize', customised: 'customized', customising: 'customizing',
  customisation: 'customization',
  anonymise: 'anonymize', anonymised: 'anonymized',
  synchronise: 'synchronize', synchronised: 'synchronized',
  synchronisation: 'synchronization',
  generalisations: 'generalizations',
  visualise: 'visualize', visualises: 'visualizes', visualising: 'visualizing',
  visualisation: 'visualization', visualisations: 'visualizations',
  normalises: 'normalizes', humanise: 'humanize', humanises: 'humanizes',
  canonicalise: 'canonicalize', canonicalised: 'canonicalized',
  systematise: 'systematize', stabilise: 'stabilize', stabilises: 'stabilizes',
  popularised: 'popularized', neutralise: 'neutralize', monetise: 'monetize',
  initialise: 'initialize', empathise: 'empathize',
  contextualise: 'contextualize',
  centralise: 'centralize', centralised: 'centralized', centralising: 'centralizing',
  cannibalise: 'cannibalize', cannibalising: 'cannibalizing',
  capitalising: 'capitalizing',
  authorises: 'authorizes', authorisation: 'authorization',
  apologise: 'apologize', agonised: 'agonized',
  // Non -ise British forms.
  colour: 'color', colours: 'colors',
  behaviour: 'behavior', behaviours: 'behaviors',
  favour: 'favor', labour: 'labor',
  centre: 'center', centres: 'centers',
  defence: 'defense', licence: 'license',
  practising: 'practicing', programme: 'program', programmes: 'programs',
  catalogue: 'catalog', catalogues: 'catalogs',
  modelling: 'modeling', labelled: 'labeled', grey: 'gray',
  analyse: 'analyze', analysing: 'analyzing', analysed: 'analyzed',
};

export const ANALYSES_NOUNS = [
  'trend analyses', 'unique analyses', 'spreadsheet analyses', 'funnel analyses',
];
