// Reads the dates generated by tools/gen-last-updated.mjs, which runs before
// the build. Kept free of Node APIs so it type-checks as ordinary app code.
import dates from '../data/last-updated.json';

/** Formatted month and year, or an empty string when git told us nothing. */
export function lastUpdated(page: keyof typeof dates): string {
  return dates[page] || '';
}
